# Generated by Django 5.0 on 2024-01-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfmp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='id_course',
        ),
    ]
