# Generated by Django 5.0 on 2024-01-20 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfmp', '0002_remove_files_id_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='id_courses',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
