# Generated by Django 5.0 on 2024-01-23 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfmp', '0003_files_id_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmp',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
